[package]
name = "gossip"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
log = "0.4.27"
maelstrom-node = "0.1.6"
serde = "1.0.219"
tokio = { version = "1" }
